import MedicalUnit from "../model/hospital/MedicalUnit";

export const MedicalUnitsArray = [
    new MedicalUnit("M1", "CV-Hospital in the Home", "Ambulatory and Community Health"),
    new MedicalUnit("M2", "Screening Clinic", "Ambulatory and Community Health"),
    new MedicalUnit("M3", "NHT East PJC", "Continuing Care"),
    new MedicalUnit("M4", "GEM East PJC", "Continuing Care"),
    new MedicalUnit("M5", "TCP West Ward PJC", "Continuing Care"),
    new MedicalUnit("M6", "Rehab AHS", "Continuing Care"),
    new MedicalUnit("M7", "GEM East WH", "Continuing Care"),
    new MedicalUnit("M8", "GEM West Ward PJC", "Continuing Care"),
    new MedicalUnit("M9", "GEM AHS", "Continuing Care"),
    new MedicalUnit("M10", "Rehab East L1 PJC", "Continuing Care"),
    new MedicalUnit("M11", "NHT Edward St", "Continuing Care"),
    new MedicalUnit("M12", "NHT Mooroolbark", "Continuing Care"),
    new MedicalUnit("M13", "NHT Northside PJC", "Continuing Care"),
    new MedicalUnit("M14", "NHT Monda Lodge", "Continuing Care"),
    new MedicalUnit("M15", "Early Supported Discharge", "Continuing Care"),
    new MedicalUnit("M16", "GEM HLS", "Continuing Care"),
    new MedicalUnit("M17", "TCP in the Community", "Continuing Care"),
    new MedicalUnit("M18", "TCP PJC", "Continuing Care"),
    new MedicalUnit("M19", "GEM Ambulatory PJC", "Continuing Care"),
    new MedicalUnit("M20", "RACS WH", "Continuing Care"),
    new MedicalUnit("M21", "Rehab Centre PJC", "Continuing Care"),
    new MedicalUnit("M22", "GEM BHH", "Continuing Care"),
    new MedicalUnit("M23", "Rehabilitation", "Continuing Care"),
    new MedicalUnit("M24", "HITH", "Continuing Care"),
    new MedicalUnit("M25", "GEM Centre PJC", "Continuing Care"),
    new MedicalUnit("M26", "GEM 1W AHS", "Continuing Care"),
    new MedicalUnit("M27", "Rehab East PJC", "Continuing Care"),
    new MedicalUnit("M28", "Palliative Care WH", "Continuing Care"),
    new MedicalUnit("M29", "GEM MAR", "Continuing Care"),
    new MedicalUnit("M30", "GEM North WH", "Continuing Care"),
    new MedicalUnit("M31", "CV-GEM 1W ANG", "Continuing Care"),
    new MedicalUnit("M32", "CV-Short Stay Unit ANG", "Emergency and General Medicine"),
    new MedicalUnit("M33", "COVID2 confirmed", "Emergency and General Medicine"),
    new MedicalUnit("M34", "COVID2 suspected", "Emergency and General Medicine"),
    new MedicalUnit("M35", "COVID1 suspected", "Emergency and General Medicine"),
    new MedicalUnit("M36", "Clinical Decision Unit", "Emergency and General Medicine"),
    new MedicalUnit("M37", "CV-Acute Med 1W ANG", "Emergency and General Medicine"),
    new MedicalUnit("M38", "CV-Acute Med MAR 3", "Emergency and General Medicine"),
    new MedicalUnit("M39", "CV-Acute Med 1 ANG", "Emergency and General Medicine"),
    new MedicalUnit("M40", "CV-Acute Care OP2 ANG", "Emergency and General Medicine"),
    new MedicalUnit("M41", "CV-Acute Care OP1 ANG", "Emergency and General Medicine"),
    new MedicalUnit("M42", "CV-Acute Med MAR 1", "Emergency and General Medicine"),
    new MedicalUnit("M43", "CV-Acute Medical 2 BHH", "Emergency and General Medicine"),
    new MedicalUnit("M44", "Acute Medical 1W AHS", "Emergency and General Medicine"),
    new MedicalUnit("M45", "Stroke/GenMed MAR", "Emergency and General Medicine"),
    new MedicalUnit("M46", "Allied Health Procedure Unit", "Emergency and General Medicine"),
    new MedicalUnit("M47", "COVID1 confirmed", "Emergency and General Medicine"),
    new MedicalUnit("M48", "Medical HLS", "Emergency and General Medicine"),
    new MedicalUnit("M49", "CV-Acute Med MAR 2", "Emergency and General Medicine"),
    new MedicalUnit("M50", "CV-Acute Medical 3 BHH", "Emergency and General Medicine"),
    new MedicalUnit("M51", "CV-Acute Medical 1 BHH", "Emergency and General Medicine"),
    new MedicalUnit("M52", "Short Stay Unit AHS", "Emergency and General Medicine"),
    new MedicalUnit("M53", "Acute Medical M3 MAR", "Emergency and General Medicine"),
    new MedicalUnit("M54", "Acute Medical BLK", "Emergency and General Medicine"),
    new MedicalUnit("M55", "Acute Care OP1", "Emergency and General Medicine"),
    new MedicalUnit("M56", "Acute Medical B3 BHH", "Emergency and General Medicine"),
    new MedicalUnit("M57", "Acute Medical B2 BHH", "Emergency and General Medicine"),
    new MedicalUnit("M58", "Acute Medical B1 BHH", "Emergency and General Medicine"),
    new MedicalUnit("M59", "Acute Medical M2 MAR", "Emergency and General Medicine"),
    new MedicalUnit("M60", "Acute Medical M1 MAR", "Emergency and General Medicine"),
    new MedicalUnit("M61", "Short Stay Unit MAR", "Emergency and General Medicine"),
    new MedicalUnit("M62", "Short Stay Unit BHH", "Emergency and General Medicine"),
    new MedicalUnit("M63", "Emergency", "Emergency and General Medicine"),
    new MedicalUnit("M64", "Acute Care OP2", "Emergency and General Medicine"),
    new MedicalUnit("M65", "Acute Medical A1 AHS", "Emergency and General Medicine"),
    new MedicalUnit("M66", "Non Admitted Turning Point", "Mental Health/Turning Point/Alcohol&Drug"),
    new MedicalUnit("M67", "ECT", "Mental Health/Turning Point/Alcohol&Drug"),
    new MedicalUnit("M68", "Psych - Aged PJC", "Mental Health/Turning Point/Alcohol&Drug"),
    new MedicalUnit("M69", "CV-Psychiatry BHH", "Mental Health/Turning Point/Alcohol&Drug"),
    new MedicalUnit("M70", "CV-Adolescent IPU BHH", "Mental Health/Turning Point/Alcohol&Drug"),
    new MedicalUnit("M71", "CV-Psych, Adult Upton BHH", "Mental Health/Turning Point/Alcohol&Drug"),
    new MedicalUnit("M72", "Drug and Alcohol", "Mental Health/Turning Point/Alcohol&Drug"),
    new MedicalUnit("M73", "Psych - Adult BHH", "Mental Health/Turning Point/Alcohol&Drug"),
    new MedicalUnit("M74", "Pysch Aged 1E BHH", "Mental Health/Turning Point/Alcohol&Drug"),
    new MedicalUnit("M75", "CV-Psych, Adult MAR", "Mental Health/Turning Point/Alcohol&Drug"),
    new MedicalUnit("M76", "Adolescent IPU BHH", "Mental Health/Turning Point/Alcohol&Drug"),
    new MedicalUnit("M77", "Psych Aged 1E BHH", "Mental Health/Turning Point/Alcohol&Drug"),
    new MedicalUnit("M78", "Psych - Adult IPU MAR", "Mental Health/Turning Point/Alcohol&Drug"),
    new MedicalUnit("M79", "Psych - Adult Upton House BHH", "Mental Health/Turning Point/Alcohol&Drug"),
    new MedicalUnit("M80", "CV-Haemostasis-Thrombosis", "Speciality Medicine"),
    new MedicalUnit("M81", "COVID4 suspected", "Speciality Medicine"),
    new MedicalUnit("M82", "COVID Observation Unit", "Speciality Medicine"),
    new MedicalUnit("M83", "COVID3 confirmed", "Speciality Medicine"),
    new MedicalUnit("M84", "COVID2 confirmed", "Speciality Medicine"),
    new MedicalUnit("M85", "COVID2 suspected", "Speciality Medicine"),
    new MedicalUnit("M86", "CV-Infectious Disease", "Speciality Medicine"),
    new MedicalUnit("M87", "CV-Oncology 4.1 BHH", "Speciality Medicine"),
    new MedicalUnit("M88", "CV-Neurology MAR", "Speciality Medicine"),
    new MedicalUnit("M89", "CV-Renal Dialysis MAR", "Speciality Medicine"),
    new MedicalUnit("M90", "Dermatology", "Speciality Medicine"),
    new MedicalUnit("M91", "CV-Renal Dialysis ANG", "Speciality Medicine"),
    new MedicalUnit("M92", "CV-Renal Dialysis BHH", "Speciality Medicine"),
    new MedicalUnit("M93", "COVID - HITH", "Speciality Medicine"),
    new MedicalUnit("M94", "CV-Haemostasis/Thromb/Lymphoma", "Speciality Medicine"),
    new MedicalUnit("M95", "COVID1 suspected", "Speciality Medicine"),
    new MedicalUnit("M96", "CV-Renal Medicine BHH", "Speciality Medicine"),
    new MedicalUnit("M97", "CV-Oncology MAR", "Speciality Medicine"),
    new MedicalUnit("M98", "CV-Stroke BHH", "Speciality Medicine"),
    new MedicalUnit("M99", "CV-Neurology Medical BHH", "Speciality Medicine"),
    new MedicalUnit("M100", "CV-Oncology 5.1 BHH", "Speciality Medicine"),
    new MedicalUnit("M101", "Plasma Exchange", "Speciality Medicine"),
    new MedicalUnit("M102", "COVID1 confirmed", "Speciality Medicine"),
    new MedicalUnit("M103", "CV-Respiratory Medicine", "Speciality Medicine"),
    new MedicalUnit("M104", "Renal Dialysis HLS", "Speciality Medicine"),
    new MedicalUnit("M105", "Haemostasis - Thrombosis", "Speciality Medicine"),
    new MedicalUnit("M106", "Rheumatology", "Speciality Medicine"),
    new MedicalUnit("M107", "Neurology MAR", "Speciality Medicine"),
    new MedicalUnit("M108", "Oncology YRH", "Speciality Medicine"),
    new MedicalUnit("M109", "Haematology MAR", "Speciality Medicine"),
    new MedicalUnit("M110", "Renal Dialysis PJC", "Speciality Medicine"),
    new MedicalUnit("M111", "Renal Dialysis MAR", "Speciality Medicine"),
    new MedicalUnit("M112", "Renal Dialysis AHS", "Speciality Medicine"),
    new MedicalUnit("M113", "CV-Cardiology", "Speciality Medicine"),
    new MedicalUnit("M114", "Non Admitted Cardiology", "Speciality Medicine"),
    new MedicalUnit("M115", "CV-Oncology BHH", "Speciality Medicine"),
    new MedicalUnit("M116", "CV-Gastroenterology", "Speciality Medicine"),
    new MedicalUnit("M117", "Renal Dialysis BHH", "Speciality Medicine"),
    new MedicalUnit("M118", "CV-Endocrinology", "Speciality Medicine"),
    new MedicalUnit("M119", "Endocrinology", "Speciality Medicine"),
    new MedicalUnit("M120", "Oncology 4.1 BHH", "Speciality Medicine"),
    new MedicalUnit("M121", "Infectious Diseases", "Speciality Medicine"),
    new MedicalUnit("M122", "Oncology 5.1 BHH", "Speciality Medicine"),
    new MedicalUnit("M123", "Haematology", "Speciality Medicine"),
    new MedicalUnit("M124", "Gastroenterology", "Speciality Medicine"),
    new MedicalUnit("M125", "Stroke BHH", "Speciality Medicine"),
    new MedicalUnit("M126", "CV-Haematology BHH", "Speciality Medicine"),
    new MedicalUnit("M127", "Renal", "Speciality Medicine"),
    new MedicalUnit("M128", "Haemostasis/Thromb/Lymphoma", "Speciality Medicine"),
    new MedicalUnit("M129", "Oncology BHH", "Speciality Medicine"),
    new MedicalUnit("M130", "Neurology BHH", "Speciality Medicine"),
    new MedicalUnit("M131", "Oncology MAR", "Speciality Medicine"),
    new MedicalUnit("M132", "Respiratory", "Speciality Medicine"),
    new MedicalUnit("M133", "Cardiology", "Speciality Medicine"),
    new MedicalUnit("M134", "CV-Non-Admit Card BHH", "Speciality Medicine"),
    new MedicalUnit("M135", "CV-Surgical 3 MAR", "Surgery"),
    new MedicalUnit("M136", "CV-Surgical 1 MAR", "Surgery"),
    new MedicalUnit("M137", "CV-Orthopaedics MAR", "Surgery"),
    new MedicalUnit("M138", "CV-Surgical 2 MAR", "Surgery"),
    new MedicalUnit("M139", "CV-Vascular Surg BHH", "Surgery"),
    new MedicalUnit("M140", "ICU", "Surgery"),
    new MedicalUnit("M141", "CV-Paeds Surgery BHH", "Surgery"),
    new MedicalUnit("M142", "CV-ENT2 BHH", "Surgery"),
    new MedicalUnit("M143", "CV-Gen Surg C BHH", "Surgery"),
    new MedicalUnit("M144", "CV-Urology", "Surgery"),
    new MedicalUnit("M145", "CV-Orthopaedics 1 BHH", "Surgery"),
    new MedicalUnit("M146", "CV-HPB & Upper GI BHH", "Surgery"),
    new MedicalUnit("M147", "Day Procedure Unit YRH", "Surgery"),
    new MedicalUnit("M148", "ENT AHS", "Surgery"),
    new MedicalUnit("M149", "Ophthalmology YRH", "Surgery"),
    new MedicalUnit("M150", "CV-Plastic Surgery", "Surgery"),
    new MedicalUnit("M151", "Surgical HLS", "Surgery"),
    new MedicalUnit("M152", "CV-Gen Surg A BHH", "Surgery"),
    new MedicalUnit("M153", "CV-Gen Surg D BHH", "Surgery"),
    new MedicalUnit("M154", "Gen Surg 1 MAR", "Surgery"),
    new MedicalUnit("M155", "Orthopaedic Surgery 2 BHH", "Surgery"),
    new MedicalUnit("M156", "CV-Gen Surgery ANG", "Surgery"),
    new MedicalUnit("M157", "Paediatric Surgery", "Surgery"),
    new MedicalUnit("M158", "General Surgery BLK", "Surgery"),
    new MedicalUnit("M159", "Thoracic Surgery", "Surgery"),
    new MedicalUnit("M160", "Gen Surg B BHH", "Surgery"),
    new MedicalUnit("M161", "Gen Surg A BHH", "Surgery"),
    new MedicalUnit("M162", "Plastic Surgery", "Surgery"),
    new MedicalUnit("M163", "Gen Surg D BHH", "Surgery"),
    new MedicalUnit("M164", "Gen Surg 3 MAR", "Surgery"),
    new MedicalUnit("M165", "Urology", "Surgery"),
    new MedicalUnit("M166", "Orthopaedic Surgery 1 BHH", "Surgery"),
    new MedicalUnit("M167", "ENT BHH", "Surgery"),
    new MedicalUnit("M168", "Gen Surg AHS", "Surgery"),
    new MedicalUnit("M169", "Orthopaedic Surgery MAR", "Surgery"),
    new MedicalUnit("M170", "Vascular Surgery", "Surgery"),
    new MedicalUnit("M171", "Gen Surg 2 MAR", "Surgery"),
    new MedicalUnit("M172", "Gen Surg C BHH", "Surgery"),
    new MedicalUnit("M173", "CV-Paeds Medicine 1 BHH", "Women and Children"),
    new MedicalUnit("M174", "CV-Obstetrics ANG", "Women and Children"),
    new MedicalUnit("M175", "CV-Paediatrics ANG", "Women and Children"),
    new MedicalUnit("M176", "CV-Maternity BHH", "Women and Children"),
    new MedicalUnit("M177", "Unqualified Newborns", "Women and Children"),
    new MedicalUnit("M178", "CV-Obs and Gynae BHH", "Women and Children"),
    new MedicalUnit("M179", "Gynaecology BLK", "Women and Children"),
    new MedicalUnit("M180", "CV-Gynaecology ANG", "Women and Children"),
    new MedicalUnit("M181", "Gynaecology AHS", "Women and Children"),
    new MedicalUnit("M182", "Paediatrics AHS", "Women and Children"),
    new MedicalUnit("M183", "Special Care Nursery", "Women and Children"),
    new MedicalUnit("M184", "Paediatrics BHH", "Women and Children"),
    new MedicalUnit("M185", "Obstetrics AHS", "Women and Children"),
    new MedicalUnit("M186", "Obs & Gynae BHH", "Women and Children"),
    new MedicalUnit("M187", "Maternity BHH", "Women and Children"),
];

// TODO: Populate with actual medical units
export const MedicalUnits = MedicalUnitsArray.reduce(
    (accumulator, medicalUnit) => {
        accumulator[medicalUnit.id] = medicalUnit;
        return accumulator;
    },
    {} as Record<string, MedicalUnit>,
);
