import Ward from "../model/hospital/Ward";

export const WardsArray = [
    new Ward("W1", "AHS", "EMER AHS"),
    new Ward("W2", "AHS", "2 West AHS"),
    new Ward("W3", "AHS", "1 North AHS"),
    new Ward("W4", "AHS", "BIRTH SUITE AHS"),
    new Ward("W5", "AHS", "DPU AHS"),
    new Ward("W6", "AHS", "NAAMAT AHS"),
    new Ward("W7", "AHS", "1 West AHS"),
    new Ward("W8", "AHS", "SCN AHS"),
    new Ward("W9", "AHS", "4E AHS"),
    new Ward("W10", "AHS", "2E AHS"),
    new Ward("W11", "AHS", "3E AHS"),
    new Ward("W12", "AHS", "UNQB3E AHS"),
    new Ward("W13", "AHS", "RDU AHS"),
    new Ward("W14", "AHS", "CDU AHS"),
    new Ward("W15", "AHS", "SSU AHS"),
    new Ward("W16", "AHS", "PATHS AHS"),
    new Ward("W17", "AHS", "CDUP AHS"),
    new Ward("W18", "AHS", "TL AHS"),
    new Ward("W19", "AHS", "3WTL AHS"),
    new Ward("W20", "AHS", "H/MID AHS"),
    new Ward("W21", "AHS", "SSUP AHS"),
    new Ward("W22", "AHS", "EMERG AHS"),
    new Ward("W23", "AHS", "FBC AHS"),
    new Ward("W24", "AHS", "ACVOBS AHS"),
    new Ward("W25", "AHS", "Angliss AHP"),
    new Ward("W26", "BLK", "Blackburn BLK"),
    new Ward("W27", "BLK", "Canterbury BLK"),
    new Ward("W28", "BLK", "Day Procedure BLK"),
    new Ward("W29", "BHH", "7.1 BHH"),
    new Ward("W30", "BHH", "Emergency BHH"),
    new Ward("W31", "BHH", "5.3 BHH"),
    new Ward("W32", "BHH", "ADOL IPU BHH"),
    new Ward("W33", "BHH", "NAMAT BHH"),
    new Ward("W34", "BHH", "Surg Admit BHH"),
    new Ward("W35", "BHH", "UPT HOUSE BHH"),
    new Ward("W36", "BHH", "4.1 BHH"),
    new Ward("W37", "BHH", "Cath Lab"),
    new Ward("W38", "BHH", "4.3 BHH"),
    new Ward("W39", "BHH", "8.2 BHH"),
    new Ward("W40", "BHH", "3.4 BHH"),
    new Ward("W41", "BHH", "HITH BHH"),
    new Ward("W42", "BHH", "Renal Dial-Home"),
    new Ward("W43", "BHH", "DIALYSIS BHH"),
    new Ward("W44", "BHH", "3.3 BHH"),
    new Ward("W45", "BHH", "9.1 BHH"),
    new Ward("W46", "BHH", "2.2 BHH"),
    new Ward("W47", "BHH", "9.2 BHH"),
    new Ward("W48", "BHH", "IMAGING BHH"),
    new Ward("W49", "BHH", "7.2 BHH"),
    new Ward("W50", "BHH", "2.1 BHH"),
    new Ward("W51", "BHH", "B1E BHH"),
    new Ward("W52", "BHH", "2.3 BHH"),
    new Ward("W53", "BHH", "6.2 BHH"),
    new Ward("W54", "BHH", "8.1 BHH"),
    new Ward("W55", "BHH", "6.1 BHH"),
    new Ward("W56", "BHH", "3.1 BHH"),
    new Ward("W57", "BHH", "NEWBORN HITH BHH"),
    new Ward("W58", "BHH", "CDU BHH"),
    new Ward("W59", "BHH", "zzzSC Box Hill"),
    new Ward("W60", "BHH", "SSU BHH"),
    new Ward("W61", "BHH", "9.3 BHH"),
    new Ward("W62", "BHH", "ENDOSCOPY  BHH"),
    new Ward("W63", "BHH", "Nursery BHH"),
    new Ward("W64", "BHH", "BALFRED BHH"),
    new Ward("W65", "BHH", "NACARD"),
    new Ward("W66", "BHH", "5.2 BHH"),
    new Ward("W67", "BHH", "5.1 BHH"),
    new Ward("W68", "BHH", "1N MHOT BHH"),
    new Ward("W69", "BHH", "Emergency Admissions BHH"),
    new Ward("W70", "BHH", "TL BHH"),
    new Ward("W71", "BHH", "NATPT BHH"),
    new Ward("W72", "BHH", "UPT HOUSE ECT BHH"),
    new Ward("W73", "BHH", "OUTPATIENT BHH"),
    new Ward("W74", "BHH", "zzzSC Mobile"),
    new Ward("W75", "BHH", "BSSU2 BHH"),
    new Ward("W76", "BHH", "BCVOBS BHH"),
    new Ward("W77", "BHH", "zzzSC Carrington"),
    new Ward("W78", "HEA", "HLS HEA"),
    new Ward("W79", "HEA", "RDUH"),
    new Ward("W80", "HEA", "THRH  HEA"),
    new Ward("W81", "HEA", "HLS AHP"),
    new Ward("W82", "HEA", "zzzScreening HEA"),
    new Ward("W83", "MAR", "EMER MAR"),
    new Ward("W84", "MAR", "DPU MAR"),
    new Ward("W85", "MAR", "DAYCHEMO MAR"),
    new Ward("W86", "MAR", "1E MAR"),
    new Ward("W87", "MAR", "PAPU MAR"),
    new Ward("W88", "MAR", "IPU1 MAR"),
    new Ward("W89", "MAR", "HIH MAR"),
    new Ward("W90", "MAR", "3N MAR"),
    new Ward("W91", "MAR", "1N MAR"),
    new Ward("W92", "MAR", "2N MAR"),
    new Ward("W93", "MAR", "ICU MAR"),
    new Ward("W94", "MAR", "SSO MAR"),
    new Ward("W95", "MAR", "ENDOSCOPY MAR"),
    new Ward("W96", "MAR", "IPU2 MAR"),
    new Ward("W97", "MAR", "2 East MAR"),
    new Ward("W98", "MAR", "DIALYSIS MAR"),
    new Ward("W99", "MAR", "TL MAR"),
    new Ward("W100", "MAR", "3E MAR"),
    new Ward("W101", "MAR", "DPA-ON MAR"),
    new Ward("W102", "MAR", "EDA MAR"),
    new Ward("W103", "MAR", "MALFRED MAR"),
    new Ward("W104", "MAR", "MAR/DPA"),
    new Ward("W105", "MAR", "CDU MAR"),
    new Ward("W106", "MAR", "Maroondah AHP"),
    new Ward("W107", "MAR", "MCVOBS MAR"),
    new Ward("W108", "PJC", "TRANS PJC"),
    new Ward("W109", "PJC", "EDW PJC"),
    new Ward("W110", "PJC", "EAST PJC"),
    new Ward("W111", "PJC", "CENTRE PJC"),
    new Ward("W112", "PJC", "SOUTH PJC"),
    new Ward("W113", "PJC", "MARTIN LUTHER HOUSE PJC"),
    new Ward("W114", "PJC", "WEST PJC"),
    new Ward("W115", "PJC", "PJC AHP"),
    new Ward("W116", "PJC", "ESSD PJC"),
    new Ward("W117", "PJC", "GEMH PJC"),
    new Ward("W118", "PJC", "RILJ PJC"),
    new Ward("W119", "PJC", "NORTH PJC"),
    new Ward("W120", "PJC", "REN PJC"),
    new Ward("W121", "PJC", "MOO PJC"),
    new Ward("W122", "PJC", "MONDA LODGE PJC"),
    new Ward("W123", "PJC", "VAC PJC"),
    new Ward("W124", "PJC", "TCP West Ward PJC"),
    new Ward("W125", "PJC", "ECT PJC"),
    new Ward("W126", "WAN", "WANTEAST WAN"),
    new Ward("W127", "WAN", "WANTNORTH WAN"),
    new Ward("W128", "WAN", "APTRE WAN"),
    new Ward("W129", "WAN", "BWREN WAN"),
    new Ward("W130", "WAN", "CHBLS WAN"),
    new Ward("W131", "WAN", "RRISE WAN"),
    new Ward("W132", "YRS", "YR ONC YRS"),
    new Ward("W133", "YRS", "DPU YRH"),
    new Ward("W134", "YRS", "HITH YRH"),
];

// TODO: Populate with the actual wards
export const Wards = WardsArray.reduce(
    (accumulator, ward) => {
        accumulator[ward.id] = ward;
        return accumulator;
    },
    {} as Record<string, Ward>,
);
